### ISSUE TITLE
Cloud Credentials

### ISSUE THREAD

**Issue by greenembrace** [openmotics/home-assistant#15]
Hi
I must have missed something somewhere....

Install using the HACS method and got to the very last step. All worked fine i had presumed.
Although I wasn't sure if the HA user should have the same name as the new OM user.

![image](https://user-images.githubusercontent.com/6187573/197371950-53c72a69-9b1e-4be8-8cfe-fc34b3bdf467.png)

log in HA

```
2022-10-23 03:17:22.148 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration openmotics which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-23 03:17:22.149 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-23 03:18:17.499 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
result = await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/openmotics/config_flow.py", line 171, in async_step_cloud
self.installations = await omclient.installations.get_all()
File "/usr/local/lib/python3.10/site-packages/pyhaopenmotics/cloud/installations.py", line 61, in get_all
return parse_obj_as(list[Installation], body["data"])
File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[list[pyhaopenmotics.cloud.models.installation.Installation]]
__root__ -> 0 -> description
none is not an allowed value (type=type_error.none.not_allowed)
```
Any help would great, I see other more knowledgeable  people have succeed so i presuming it's me.

thanks

**Comment by woutercoppens** [comment]
It's failing to retrieve all the installations you have access to.

If you login to cloud.openmotics.com and click on your name at the top
left, and then 'manage your installations'. What does it show?

**Comment by greenembrace** [comment]
Hi thanks,
I only have the one...

![image](https://user-images.githubusercontent.com/6187573/197418142-be754efb-384a-4425-bcca-4302e8e547af.png)

**Comment by woutercoppens** [comment]
Updated pyhaopenmotics so description in installation can be None. 
Please do 'ha core rebuild' and try again.

**Comment by greenembrace** [comment]
Hi Wouter,
Sorry I'm back on the wagon, I have rebuilt my home automation server, including a fresh docker image of HA, went through the above steps again including creating a new integration credentials in Openmotics and still get error although it has changed:

~~~
2022-11-13 15:03:17.988 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
result = await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/openmotics/config_flow.py", line 147, in async_step_cloud
token = await self.flow_impl.async_resolve_external_data(
File "/config/custom_components/openmotics/oauth_impl.py", line 53, in async_resolve_external_data
return await self._token_request(
File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 205, in _token_request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.openmotics.com/api/v1.1/authentication/oauth2/token')
~~~

kind regards daniel

**Comment by greenembrace** [comment]
Hi
I've now done this a couple of times and getting the same result. I'm sure it's all my fault, old slow brain. any thoughts where i should pursue my investigation? 
I'm sorry to annoy

**Comment by woutercoppens** [comment]
https://github.com/openmotics/home-assistant (See instructions)

Make sure the Client type is Confidential and the Grant type is Client credentials. ;-)

**Comment by greenembrace** [comment]
Humble apologies, on one of those retries, one Credentials was missed.
thank-you for you patience.

kind regards
